name: Tests CI
on:
push:
 branches:
 - main
pull_request:
 branches:
 - main
jobs:
test:
 runs-on: ubuntu-latest
 steps:
 - name: Cloner le repo
 uses: actions/checkout@v3
 - name: Installer Node.js
 uses: actions/setup-node@v3
 with:
 node-version: 18
 - name: Installer Cypress
 run: npm install cypress --save-dev
 - name: Exécuter ESLint
 run: npx eslint script.js
 - name: Exécuter Cypress
 run: npx cypress run
